[package]
name = "rget"
version = "0.1.0"
edition = "2018"
authors = ["Your Name <you@example.com>"]

[dependencies]
clap = "2.34.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
indicatif = "0.17"
console = "0.15"
colored = "2.1"
